# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

url: "http://draft.netlicensing.io"
google_analytics_tracking_id:
quantcast_code:
yandex_metrika_tracking_id:
